# Generated by Django 5.0.3 on 2025-12-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('guest', 'Гость'), ('user', 'Пользователь'), ('admin', 'Администратор')], default='user', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
