# Generated by Django 5.0.3 on 2025-12-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('guest', 'Гость'), ('user', 'Пользователь'), ('admin', 'Администратор')], default='guest', max_length=20, verbose_name='Роль'),
        ),
    ]
