# Generated by Django 5.0.3 on 2025-12-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_bestseller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
        migrations.AlterField(
            model_name='product',
            name='image_filename',
            field=models.FilePathField(help_text='Выберите файл из static/main/img/flowers', match='.*\\.(jpg|jpeg|png|gif)$', max_length=200, path='C:\\Users\\Lenovo\\OneDrive\\Desktop\\Практика магазин цветов django\\dev env\\app1\\static\\main\\img\\flowers', verbose_name='Имя файла изображения'),
        ),
    ]
