# Generated by Django 5.0.3 on 2025-12-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_on_main',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
    ]
